### ISSUE TITLE
Test Mode

### ISSUE THREAD

**Issue by will-wright1** [do-it-well/magento2-module-awin#1]
Hello

This module is great and works perfectly, apart from testmode= never has the value on the end of it.

Looking at OrderConfirmation I can see 'testmode' => $awin_data['awin_is_test'] ? '1' : '0'

The '1' : '0' confuses me slightly, are you not getting this value from the db?

Same applies to order_confirmation.phtml although I'm assume OrderConfirmation.php constructs the URL?

AWIN.Tracking.Sale.test = <?= json_encode((string)($block->getAwinIsTest() ? 1 : 0)); ?>;

I'm using M2.3.1 

I can see the value in the database in core_config_data

**Comment by wpalmer** [comment]
Thank you for the report. This issue has now been corrected.

The issue stemmed from a couple of different sources. Firstly, we were erroneously using `escapeUrl(...)` rather than `encodeUrlParam(...)` to URL-Encode the values.

However, due to what I think is a bug in magento, `encodeUrlParam` is (internally) the same as `escapeUrl` anyway.

However, due to a different bug in magento, the string `"0"` was being converted into an empty string. This bug has been reported here: https://github.com/magento/magento2/issues/23987 (and a pull request created to correct the issue)

In the meantime, because `encodeUrlParam` does not appear to "do the right thing" in the first place, this issue has been changed to call PHP's builtin `urlencode` directly, instead. This not only corrects the bug of parameters not being url-encoded correctly, but also bypasses the issue in Magento.

To answer your other question: we specify `'1'` and `'0'` specifically, even though the value from the database is probably the same anyway, because the value we read from the database is logically being used as a boolean variable, while the strings `'1'` and `'0'` are part of the specification from AWIN of what the parameter should hold. In short: we do this to remove the sort of ambiguity which caused this bug in the first place! (ie: treating "truthy" strings as logically equivalent to boolean values).

This has been corrected in version 1.0.2, which is now available in Packagist / Composer

**Comment by will-wright1** [comment]
Thanks @wpalmer
